services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=backend.app
      - FLASK_ENV=production
      - STORAGE_DIR=/app/storage
      - UPLOAD_FOLDER=/app/uploads
      - QDRANT_HOST=qdrant
    volumes:
      - uploads_data:/app/uploads
      - storage_data:/app/storage
      - ./.env:/app/.env
    depends_on:
      - qdrant
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network

volumes:
  qdrant_storage:
  uploads_data:
  storage_data:  # Volume for persistent conversation storage

networks:
  app-network:
    driver: bridge